# Generated by Django 5.2.8 on 2025-12-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='riwayatkonfigurasi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='riwayat_images/'),
        ),
    ]
