# Generated by Django 5.2.8 on 2025-12-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_image_riwayatkonfigurasi_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='topology_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
