# Generated by Django 5.2.8 on 2025-12-17 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat_topology_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=100, unique=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='api.networkdevice')),
            ],
        ),
    ]
