- name: Apply config to network device
  hosts: all
  gather_facts: no

  tasks:
    # MIKROTIK
    - name: Apply config to Mikrotik RouterOs
      community.routeros.command:
        commands: "{{ config_cli }}"
      when: ansible_network_os == "routeros"
      register: mikrotik_result  
      
      failed_when: 
        - mikrotik_result.failed == true or
          "bad command" in (mikrotik_result | string | lower) or
          "syntax error" in (mikrotik_result | string | lower) or
          "expected end" in (mikrotik_result | string | lower) or
          "input does not match" in (mikrotik_result | string | lower) or
          "no such item" in (mikrotik_result | string | lower)

    # HUAWEI CE
    - name: Apply config to Huawei CE
      community.network.ce_config:
        lines: "{{ config_cli }}"
      when: ansible_network_os == 'ce'
      register: ce_result

      failed_when:
        - ce_result.failed == true or
          "unrecognized command" in (ce_result | string | lower) or
          "wrong parameter" in (ce_result | string | lower) or
          "error:" in (ce_result | string | lower) or
          "incomplete command" in (ce_result | string | lower) or
          "ambiguous command" in (ce_result | string | lower)

    # 3. HUAWEI VRP 
    - name: Apply config to Huawei VRP
      ansible.netcommon.cli_command:
        lines: "{{ config_cli }}"
      when: ansible_network_os == 'vrp'
      register: vrp_result

      failed_when:
        - vrp_result.failed == true or
          "unrecognized command" in (vrp_result | string | lower) or
          "wrong parameter" in (vrp_result | string | lower) or
          "error:" in (vrp_result | string | lower) or
          "incomplete command" in (vrp_result | string | lower) or
          "ambiguous command" in (vrp_result | string | lower)

    # Menampilkan Hasil Eksekusi Perangkat
    - name: "Tampilkan Hasil Eksekusi Perangkat"
      debug:
        msg: 
          - "=== OUTPUT MIKROTIK ==="
          - "{{ mikrotik_result.stdout_lines | default('N/A') }}"
          - "=== OUTPUT HUAWEI CE ==="
          - "{{ ce_result.commands | default('N/A') }}"
          - "=== OUTPUT HUAWEI VRP ==="
          - "{{ vrp_result.commands | default('N/A') }}"
