- name: Apply config to network device
  hosts: all
  gather_facts: no

  tasks:
    - name: Apply config to Mikrotik RouterOs
      ansible.netcommon.cli_command:
        command: "{{ item }}"
      loop: "{{ config_cli.split(' ; ') }}"
      when: ansible_network_os == "community.routeros.routeros" and item | trim != ''
      register: mikrotik_result  
      ignore_errors: yes

      failed_when: >
        mikrotik_result.failed == true or
        'bad command' in (mikrotik_result.stdout | default('') | lower) or
        'syntax error' in (mikrotik_result.stdout | default('') | lower) or
        'expected end' in (mikrotik_result.stdout | default('') | lower) or
        'input does not match' in (mikrotik_result.stdout | default('') | lower) or
        'no such item' in (mikrotik_result.stdout | default('') | lower)

      changed_when: >
        mikrotik_result.failed == false and
        'bad command' not in (mikrotik_result.stdout | default('') | lower) and
        'syntax error' not in (mikrotik_result.stdout | default('') | lower) and
        'expected end' not in (mikrotik_result.stdout | default('') | lower) and
        'input does not match' not in (mikrotik_result.stdout | default('') | lower) and
        'no such item' not in (mikrotik_result.stdout | default('') | lower)


    - name: Apply config to Huawei
      community.network.ce_command:
        # Kirim semua baris perintah sekaligus dalam bentuk list (tanpa loop!)
        commands: "{{ ['system-view'] + config_cli.split('\n') + ['return'] }}"
      when: ansible_network_os == 'community.network.ce' and config_cli | trim != ''
      register: huawei_result
      ignore_errors: yes

      failed_when: >
        huawei_result.failed == true or
        "Error:" in (huawei_result.stdout | join(' ') | string) or
        "Unrecognized" in (huawei_result.stdout | join(' ') | string)
        
      changed_when: >
        huawei_result.failed == false and
        "Error:" not in (huawei_result.stdout | join(' ') | string) and
        "Unrecognized" not in (huawei_result.stdout | join(' ') | string)
      
    - name: "Tampilkan Hasil Eksekusi Perangkat"
      debug:
        msg: 
          - "=== OUTPUT MIKROTIK ==="
          - "{{ mikrotik_result.results | default([]) | map(attribute='stdout') | list | default('N/A') }}"
          - "=== OUTPUT HUAWEI ==="
          - "{{ huawei_result.stdout | default('N/A') }}"
