- name: Apply config to network device
  hosts: all
  gather_facts: no

  tasks:
    # MIKROTIK
    - name: Apply config to Mikrotik RouterOs
      community.routeros.command:
        commands: "{{ config_cli }}"
      when: ansible_network_os == "routeros"
      register: mikrotik_result  
      
      failed_when: 
        - mikrotik_result.failed == true or
          "bad command" in mikrotik_result.stdout[0] | lower or
          "syntax error" in mikrotik_result.stdout[0] | lower or
          "expected end" in mikrotik_result.stdout[0] | lower or
          "input does not match" in mikrotik_result.stdout[0] | lower or
          "no such item" in mikrotik_result.stdout[0] | lower

    # HUAWEI
    - name: Apply config to Huawei
      ansible.netcommon.cli_command:
        command: "{{ item }}"
      loop: "{{ config_cli.split('\n') | map('trim') | reject('equalto', '') | list }}"
      when: ansible_network_os == "generic"
      register: huawei_result
      
      failed_when: 
        - '"Error:" in huawei_result.stdout | default("")'
        - '"Unrecognized command" in huawei_result.stdout | default("")'
