- name: Read data from network device
  hosts: all
  gather_facts: no

  tasks:
    # MIKROTIK
    - name: Run command on Mikrotik
      community.routeros.command:
        commands: "{{ target_command }}"
      when: ansible_network_os == "routeros"
      register: mikrotik_out

    # HUAWEI CE
    - name: Run command on Huawei CE
      community.network.ce_command:
        commands: "{{ target_command }}"
      when: ansible_network_os == 'ce'
      register: ce_out

    # HUAWEI VRP
    - name: Run command on Huawei VRP
      ansible.netcommon.cli_command:
        commands: "{{ target_command }}"
      when: ansible_network_os == 'vrp'
      register: vrp_out

    # Menampilkan Hasil
    - name: "Output Eksekusi"
      debug:
        msg: >
          {% if ansible_network_os == 'routeros' %}
          {{ mikrotik_out.stdout_lines | default('Tidak ada output') }}
          {% elif ansible_network_os == 'ce' %}
          {{ ce_out.stdout | default('Tidak ada output') }}
          {% elif ansible_network_os == 'vrp' %}
          {{ vrp_out.stdout | default('Tidak ada output') }}
          {% endif %}
