- name: Read data from network device
  hosts: all
  gather_facts: no

  tasks:
    # 1. MIKROTIK
    - name: Run command on Mikrotik
      community.routeros.command:
        commands: "{{ target_command }}"
      when: ansible_network_os == "community.routeros.routeros"
      register: mikrotik_out

    # 2. HUAWEI CE & VRP (Digabung menggunakan modul universal!)
    - name: Run command on Huawei (CE & VRP)
      ansible.netcommon.cli_command:
        command: "{{ target_command }}"
      when: ansible_network_os in ['community.network.ce', 'community.network.vrp']
      register: huawei_out

    # 3. TAMPILKAN HASILNYA KE STDOUT
    - name: "Output Eksekusi"
      debug:
        msg: >
          {% if ansible_network_os == 'community.routeros.routeros' %}
          {{ mikrotik_out.stdout[0] | default('Tidak ada output') }}
          {% elif ansible_network_os in ['community.network.ce', 'community.network.vrp'] %}
          {{ huawei_out.stdout | default('Tidak ada output') }}
          {% endif %}
